import type { Lead, LeadStatus } from "@/types";

export const LEAD_STATUS_ORDER: LeadStatus[] = [
  "NEW",
  "IN_CONTACT",
  "APPOINTMENT_SET",
  "ESTIMATION_DONE",
  "MANDATE_SIGNED",
  "LOST",
];

export const mockLeads: Lead[] = [
  {
    id: "1",
    firstName: "Jean",
    lastName: "Dupont",
    email: "jean.dupont@email.com",
    phone: "06 12 34 56 78",
    propertyAddress: "12 rue de la Paix, 75002 Paris",
    propertyType: "Appartement",
    propertySize: "65 m²",
    source: "PORTAL_SELOGER",
    status: "NEW",
    assignedTo: { id: "u1", name: "Marie Martin" },
    lastAction: "SMS envoyé",
    nextActionAt: "Dans 2h",
    createdAt: "2026-03-02T09:00:00Z",
    updatedAt: "2026-03-02T09:00:00Z",
  },
  {
    id: "2",
    firstName: "Sophie",
    lastName: "Leroy",
    email: "sophie.leroy@email.com",
    phone: "06 98 76 54 32",
    propertyAddress: "8 avenue des Champs, 75008 Paris",
    propertyType: "Appartement",
    propertySize: "90 m²",
    source: "WEBSITE",
    status: "NEW",
    assignedTo: { id: "u1", name: "Marie Martin" },
    lastAction: "Email de confirmation",
    nextActionAt: "J+1",
    createdAt: "2026-03-01T14:30:00Z",
    updatedAt: "2026-03-01T14:30:00Z",
  },
  {
    id: "3",
    firstName: "Pierre",
    lastName: "Martin",
    email: "pierre.martin@email.com",
    phone: "07 11 22 33 44",
    propertyAddress: "5 rue du Commerce, 75015 Paris",
    source: "PORTAL_LEBONCOIN",
    status: "IN_CONTACT",
    assignedTo: { id: "u2", name: "Jean Négociateur" },
    lastAction: "Appel passé",
    nextActionAt: "Demain 10h",
    createdAt: "2026-02-28T11:00:00Z",
    updatedAt: "2026-03-02T08:00:00Z",
  },
  {
    id: "4",
    firstName: "Marie",
    lastName: "Bernard",
    email: "marie.bernard@email.com",
    phone: "06 55 66 77 88",
    propertyAddress: "3 place de la République, 69003 Lyon",
    propertyType: "Maison",
    propertySize: "120 m²",
    source: "MANUAL",
    status: "APPOINTMENT_SET",
    assignedTo: { id: "u1", name: "Marie Martin" },
    lastAction: "RDV confirmé",
    nextActionAt: "05/03 14h",
    createdAt: "2026-02-25T09:00:00Z",
    updatedAt: "2026-03-01T16:00:00Z",
  },
  {
    id: "5",
    firstName: "Luc",
    lastName: "Petit",
    email: "luc.petit@email.com",
    phone: "06 99 88 77 66",
    propertyAddress: "20 boulevard Haussmann, 75009 Paris",
    propertyType: "Appartement",
    propertySize: "75 m²",
    source: "PORTAL_BIENICI",
    status: "ESTIMATION_DONE",
    estimatedValue: 450000,
    assignedTo: { id: "u2", name: "Jean Négociateur" },
    lastAction: "Estimation remise",
    nextActionAt: "Relance J+5",
    createdAt: "2026-02-20T10:00:00Z",
    updatedAt: "2026-02-28T17:00:00Z",
  },
  {
    id: "6",
    firstName: "Claire",
    lastName: "Durand",
    email: "claire.durand@email.com",
    phone: "07 00 11 22 33",
    propertyAddress: "15 rue de Rivoli, 75001 Paris",
    propertyType: "Appartement",
    propertySize: "55 m²",
    source: "WEBSITE",
    status: "MANDATE_SIGNED",
    mandateType: "EXCLUSIVE",
    assignedTo: { id: "u1", name: "Marie Martin" },
    lastAction: "Mandat signé",
    createdAt: "2026-02-15T09:00:00Z",
    updatedAt: "2026-02-25T14:00:00Z",
  },
  {
    id: "7",
    firstName: "Thomas",
    lastName: "Moreau",
    email: "thomas.moreau@email.com",
    phone: "06 44 55 66 77",
    propertyAddress: "7 rue de la Pompe, 75116 Paris",
    source: "OTHER",
    status: "LOST",
    lostReason: "Injoignable",
    assignedTo: { id: "u2", name: "Jean Négociateur" },
    lastAction: "Multiples relances sans réponse",
    createdAt: "2026-02-10T09:00:00Z",
    updatedAt: "2026-02-20T12:00:00Z",
  },
];
