import type { WhatsAppMessage } from "@/types";

export const mockWhatsAppConversations: Record<string, WhatsAppMessage[]> = {
  // Lead 8 - Camille Rousseau - Qualification en cours
  "8": [
    {
      id: "wa-8-1",
      leadId: "8",
      direction: "OUTBOUND",
      type: "TEMPLATE",
      content: "Bonjour Camille ! Merci pour votre demande d'estimation pour votre bien au 25 rue Oberkampf. Je suis Marie Martin de l'Agence Demo. Puis-je vous poser quelques questions pour mieux comprendre votre projet ?",
      timestamp: "2026-03-02T11:30:00Z",
      isAutomatic: true,
    },
    {
      id: "wa-8-2",
      leadId: "8",
      direction: "INBOUND",
      type: "TEXT",
      content: "Bonjour Marie, oui bien sûr !",
      timestamp: "2026-03-02T11:45:00Z",
      isAutomatic: false,
    },
    {
      id: "wa-8-3",
      leadId: "8",
      direction: "OUTBOUND",
      type: "TEXT",
      content: "Super ! Quel est votre budget approximatif pour ce projet ?",
      timestamp: "2026-03-02T11:46:00Z",
      isAutomatic: true,
    },
    {
      id: "wa-8-4",
      leadId: "8",
      direction: "INBOUND",
      type: "TEXT",
      content: "Entre 250 000 et 350 000€ je dirais",
      timestamp: "2026-03-02T12:10:00Z",
      isAutomatic: false,
    },
    {
      id: "wa-8-5",
      leadId: "8",
      direction: "OUTBOUND",
      type: "TEXT",
      content: "Merci ! Et quelle est votre motivation principale ? Vente, investissement, mutation ?",
      timestamp: "2026-03-02T12:11:00Z",
      isAutomatic: true,
    },
    {
      id: "wa-8-6",
      leadId: "8",
      direction: "INBOUND",
      type: "TEXT",
      content: "C'est pour vendre, je déménage bientôt en province",
      timestamp: "2026-03-02T13:30:00Z",
      isAutomatic: false,
    },
    {
      id: "wa-8-7",
      leadId: "8",
      direction: "OUTBOUND",
      type: "TEXT",
      content: "Compris ! Dans quel délai souhaitez-vous finaliser la vente ?",
      timestamp: "2026-03-02T13:31:00Z",
      isAutomatic: true,
    },
  ],
  // Lead 9 - Antoine Dubois - Qualifié hésitant
  "9": [
    {
      id: "wa-9-1",
      leadId: "9",
      direction: "OUTBOUND",
      type: "TEMPLATE",
      content: "Bonjour Antoine ! Merci pour votre intérêt pour le bien au 10 rue de Ménilmontant. Je suis Jean de l'Agence Demo. Puis-je vous poser quelques questions ?",
      timestamp: "2026-02-27T08:30:00Z",
      isAutomatic: true,
    },
    {
      id: "wa-9-2",
      leadId: "9",
      direction: "INBOUND",
      type: "TEXT",
      content: "Oui allez-y",
      timestamp: "2026-02-27T09:00:00Z",
      isAutomatic: false,
    },
    {
      id: "wa-9-3",
      leadId: "9",
      direction: "OUTBOUND",
      type: "TEXT",
      content: "Quel est votre budget pour cet investissement ?",
      timestamp: "2026-02-27T09:01:00Z",
      isAutomatic: true,
    },
    {
      id: "wa-9-4",
      leadId: "9",
      direction: "INBOUND",
      type: "TEXT",
      content: "150-200k€ max, c'est pour du locatif",
      timestamp: "2026-02-27T10:15:00Z",
      isAutomatic: false,
    },
    {
      id: "wa-9-5",
      leadId: "9",
      direction: "OUTBOUND",
      type: "TEXT",
      content: "D'accord ! Quel est votre délai pour concrétiser ?",
      timestamp: "2026-02-27T10:16:00Z",
      isAutomatic: true,
    },
    {
      id: "wa-9-6",
      leadId: "9",
      direction: "INBOUND",
      type: "TEXT",
      content: "Pas pressé, plutôt dans 6 mois ou plus. Je regarde juste les opportunités",
      timestamp: "2026-02-27T14:00:00Z",
      isAutomatic: false,
    },
    {
      id: "wa-9-7",
      leadId: "9",
      direction: "OUTBOUND",
      type: "TEXT",
      content: "Merci Antoine. Je vous envoie quelques biens qui pourraient correspondre à votre recherche.",
      timestamp: "2026-02-27T14:01:00Z",
      isAutomatic: true,
    },
    {
      id: "wa-9-8",
      leadId: "9",
      direction: "OUTBOUND",
      type: "PROPERTY_LISTING",
      content: "Studio 35m² - 10 rue de Ménilmontant, 75020 Paris\nPrix : 185 000 €\nRendement locatif estimé : 5.2%",
      timestamp: "2026-02-27T14:02:00Z",
      isAutomatic: true,
      metadata: { propertyId: "prop-1", price: "185000", yield: "5.2%" },
    },
    {
      id: "wa-9-9",
      leadId: "9",
      direction: "INBOUND",
      type: "TEXT",
      content: "Intéressant merci, je regarde ça",
      timestamp: "2026-02-28T09:00:00Z",
      isAutomatic: false,
    },
    {
      id: "wa-9-10",
      leadId: "9",
      direction: "OUTBOUND",
      type: "TEXT",
      content: "N'hésitez pas si vous avez des questions. Je reste disponible !",
      timestamp: "2026-02-28T09:01:00Z",
      isAutomatic: true,
    },
  ],
  // Lead 10 - Léa Fontaine - Qualifiée hot, Calendly envoyé
  "10": [
    {
      id: "wa-10-1",
      leadId: "10",
      direction: "OUTBOUND",
      type: "TEMPLATE",
      content: "Bonjour Léa ! Merci pour votre demande concernant le 42 avenue Victor Hugo. Je suis Marie Martin de l'Agence Demo. Quelques questions rapides pour bien vous accompagner ?",
      timestamp: "2026-03-01T07:30:00Z",
      isAutomatic: true,
    },
    {
      id: "wa-10-2",
      leadId: "10",
      direction: "INBOUND",
      type: "TEXT",
      content: "Bonjour ! Oui avec plaisir",
      timestamp: "2026-03-01T07:35:00Z",
      isAutomatic: false,
    },
    {
      id: "wa-10-3",
      leadId: "10",
      direction: "OUTBOUND",
      type: "TEXT",
      content: "Quel est votre budget pour ce bien ?",
      timestamp: "2026-03-01T07:36:00Z",
      isAutomatic: true,
    },
    {
      id: "wa-10-4",
      leadId: "10",
      direction: "INBOUND",
      type: "TEXT",
      content: "On vise entre 800k et 1M€. Notre famille s'agrandit, on cherche plus grand rapidement !",
      timestamp: "2026-03-01T07:40:00Z",
      isAutomatic: false,
    },
    {
      id: "wa-10-5",
      leadId: "10",
      direction: "OUTBOUND",
      type: "TEXT",
      content: "Félicitations ! Quel est votre délai idéal ?",
      timestamp: "2026-03-01T07:41:00Z",
      isAutomatic: true,
    },
    {
      id: "wa-10-6",
      leadId: "10",
      direction: "INBOUND",
      type: "TEXT",
      content: "1-2 mois si possible, on est vraiment motivés",
      timestamp: "2026-03-01T07:45:00Z",
      isAutomatic: false,
    },
    {
      id: "wa-10-7",
      leadId: "10",
      direction: "OUTBOUND",
      type: "TEXT",
      content: "Parfait ! Votre profil est idéal. Je vous propose de prendre rendez-vous directement pour une estimation de votre bien actuel.",
      timestamp: "2026-03-01T07:46:00Z",
      isAutomatic: true,
    },
    {
      id: "wa-10-8",
      leadId: "10",
      direction: "OUTBOUND",
      type: "CALENDLY_LINK",
      content: "Prenez rendez-vous pour votre estimation gratuite",
      timestamp: "2026-03-01T07:47:00Z",
      isAutomatic: true,
      metadata: { url: "https://calendly.com/agence-demo/estimation-lea" },
    },
    {
      id: "wa-10-9",
      leadId: "10",
      direction: "INBOUND",
      type: "TEXT",
      content: "Super merci ! Je réserve un créneau tout de suite",
      timestamp: "2026-03-01T08:00:00Z",
      isAutomatic: false,
    },
    {
      id: "wa-10-10",
      leadId: "10",
      direction: "OUTBOUND",
      type: "TEXT",
      content: "Parfait Léa ! J'ai bien reçu votre réservation. À très bientôt !",
      timestamp: "2026-03-02T09:30:00Z",
      isAutomatic: false,
    },
  ],
  // Lead 1 - Jean Dupont - Début de conversation
  "1": [
    {
      id: "wa-1-1",
      leadId: "1",
      direction: "OUTBOUND",
      type: "TEMPLATE",
      content: "Bonjour Jean ! Merci pour votre demande d'estimation pour votre bien au 12 rue de la Paix. Je suis Marie Martin de l'Agence Demo. Avez-vous quelques minutes pour échanger ?",
      timestamp: "2026-03-02T09:02:00Z",
      isAutomatic: true,
    },
    {
      id: "wa-1-2",
      leadId: "1",
      direction: "INBOUND",
      type: "TEXT",
      content: "Bonjour, oui je suis disponible",
      timestamp: "2026-03-02T09:30:00Z",
      isAutomatic: false,
    },
    {
      id: "wa-1-3",
      leadId: "1",
      direction: "OUTBOUND",
      type: "TEXT",
      content: "Super ! Quel est votre budget approximatif et votre projet (vente, investissement...) ?",
      timestamp: "2026-03-02T09:31:00Z",
      isAutomatic: true,
    },
  ],
};
